name: Web Deploy Staging
on:
  push:
    branches: [ main ]
env:
  WEBAPP_S3_BUCKET: pangea-staging-webapp
  CF_DISTRIBUTION_ID: E3KCU729VPE6GG
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:3.0.5
    steps:
      - uses: actions/checkout@v3
      - run: cp .env.staging .env.development
      - run: |
          sudo apt update && sudo apt install curl -y
          chmod -R 0777 scripts
      - run: ./scripts/prepare-web.sh
      - run: ./scripts/build-web.sh
      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: ./build/web
  deploy_staging:
    name: Upload S3
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: web
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to S3
      run: aws s3 sync . s3://$WEBAPP_S3_BUCKET
    - name: Invalidate cache
      run: |
        aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths "/*"